
-- -----------------------------------------------------
-- Table `FIREALARM_DEVICE`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `VIRTUAL_FIREALARM_DEVICE` (
  `VIRTUAL_FIREALARM_DEVICE_ID` VARCHAR(45) NOT NULL ,
  `DEVICE_NAME` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`VIRTUAL_FIREALARM_DEVICE_ID`) );

CREATE  TABLE IF NOT EXISTS `VIRTUAL_FIREALARM_DEVICE_SENSORS` (
    `SENSOR_IDENTIFIER`          VARCHAR(45)             NOT NULL,
    `DEVICE_IDENTIFIER`          VARCHAR(45)             NOT NULL,
    `SENSOR_TYPE_NAME`           VARCHAR(300)            NOT NULL,
    PRIMARY KEY (`SENSOR_IDENTIFIER`, `DEVICE_IDENTIFIER`),
    CONSTRAINT fk_VIRTUAL_FIREALARM_DEVICE_SENSORS_VIRTUAL_FIREALARM_DEVICE
        FOREIGN KEY (DEVICE_IDENTIFIER )
        REFERENCES VIRTUAL_FIREALARM_DEVICE (VIRTUAL_FIREALARM_DEVICE_ID)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT uc_DEVICE_ID_TO_SENSOR_NAME UNIQUE (`DEVICE_IDENTIFIER`,`SENSOR_TYPE_NAME`)
);

CREATE TABLE IF NOT EXISTS VIRTUAL_FIREALARM_SENSOR_DYNAMIC_PROPERTIES (
    SENSOR_IDENTIFIER    VARCHAR(45)            NOT NULL,
    PROPERTY_KEY         VARCHAR(500)           NOT NULL,
    PROPERTY_VALUE       VARCHAR(500)           DEFAULT NULL,
    PRIMARY KEY (`SENSOR_IDENTIFIER`),
    CONSTRAINT fk_VIRTUAL_FIREALARM_SENSOR_ID_PROPERTY
        FOREIGN KEY (SENSOR_IDENTIFIER)
        REFERENCES VIRTUAL_FIREALARM_DEVICE_SENSORS (SENSOR_IDENTIFIER)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT uc_SENSOR_IDENTITY_PROP_KEY UNIQUE (`SENSOR_IDENTIFIER`,`PROPERTY_KEY`)
);