
-- -----------------------------------------------------
-- Table `FIREALARM_DEVICE`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `VIRTUAL_FIREALARM_DEVICE` (
  `VIRTUAL_FIREALARM_DEVICE_ID` VARCHAR(45) NOT NULL ,
  `DEVICE_NAME` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`VIRTUAL_FIREALARM_DEVICE_ID`) );

CREATE  TABLE IF NOT EXISTS `VIRTUAL_FIREALARM_DEVICE_SENSORS` (
    `SENSOR_ID`             VARCHAR(45)             NOT NULL,
    `DEVICE_ID`             VARCHAR(45)             NOT NULL,
    `DEVICE_TYPE_SENSOR`    BLOB                    NOT NULL,
    `DYNAMIC_PROPERTIES`    BLOB                    NULL DEFAULT NULL,
    PRIMARY KEY (`SENSOR_ID`, `DEVICE_ID`)
    CONSTRAINT fk_VIRTUAL_FIREALARM_DEVICE_SENSORS_VIRTUAL_FIREALARM_DEVICE
        FOREIGN KEY (DEVICE_ID )
        REFERENCES VIRTUAL_FIREALARM_DEVICE (VIRTUAL_FIREALARM_DEVICE_ID)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);