/*
 * Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
 *
 * WSO2 Inc. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.wso2.carbon.device.mgt.iot.virtualfirealarm.scep.service.impl;

import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Response;
import java.io.InputStream;


public interface VirtualFireAlarmScepServer {

    /**
     * This is an API called/used by the SCEP Client of the VirtualFirealarm device in its SCEP enrollment process.
     * This acts as the endpoint exposed as part of the SCEP-Server for use by a SCEP Client. This is one of the two
     * method-signatures that takes different parameters according to the SCEP-Operation executed by the SCEP-Client
     * of the enrolling device. The API supports 2 SCEP Operations [GetCACert] and [GetCACaps].
     * <p/>
     * Operation [GetCACert] returns the CA cert of the SCEP-Server for the device to verify its authenticity.
     * Operation [GetCACaps] returns the CA Capabilities of the SCEP-Server.
     *
     * @param operation the SCEP operation requested by the client. [GetCACert] or [GetCACaps]
     * @param message   any messages pertaining to the requested SCEP Operation.
     * @return an HTTP Response object with either the CA-Cert or the CA-Capabilities according to the operation.
     */
    @GET
    @Path("scep")
    Response scepRequest(@QueryParam("operation") String operation, @QueryParam("message") String message);


    /**
     * This is an API called/used by the SCEP Client of the VirtualFirealarm device in its SCEP enrollment process.
     * This acts as the endpoint exposed as part of the SCEP-Server for use by a SCEP Client. This is one of the two
     * method-signatures that takes different parameters according to the SCEP-Operation executed by the SCEP-Client
     * of the enrolling device. This API supports the SCEP Operation [PKIOperation].
     * <p/>
     * Operation [PKIOperation] returns a certificate generated by the SCEP-Server for the enrolling device.
     *
     * @param operation   the final SCEP operation executed in the enrollment process - which is [PKIOperation]
     * @param inputStream an input stream consisting of the Certificate-Signing-Request (CSR) from the device.
     * @return an HTTP Response object with the signed certificate for the device by the CA of the SCEP Server.
     */
    @POST
    @Path("scep")
    Response scepRequestPost(@QueryParam("operation") String operation, InputStream inputStream);

}
