
-- -----------------------------------------------------
-- Table `AD_DEVICE`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `AD_DEVICE` (
  `MOBILE_DEVICE_ID` VARCHAR(45) NOT NULL ,
  `PUSH_TOKEN` VARCHAR(45) NULL DEFAULT NULL ,
  `IMEI` VARCHAR(45) NULL DEFAULT NULL ,
  `IMSI` VARCHAR(45) NULL DEFAULT NULL ,
  `OS_VERSION` VARCHAR(45) NULL DEFAULT NULL ,
  `DEVICE_MODEL` VARCHAR(45) NULL DEFAULT NULL ,
  `VENDOR` VARCHAR(45) NULL DEFAULT NULL ,
  `LATITUDE` VARCHAR(45) NULL DEFAULT NULL,
  `LONGITUDE` VARCHAR(45) NULL DEFAULT NULL,
  `CHALLENGE` VARCHAR(45) NULL DEFAULT NULL,
  `TOKEN` VARCHAR(500) NULL DEFAULT NULL,
  `UNLOCK_TOKEN` VARCHAR(500) NULL DEFAULT NULL,
  `SERIAL` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`MOBILE_DEVICE_ID`) );

-- -----------------------------------------------------
-- Table `AD_FEATURE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AD_FEATURE` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `CODE` VARCHAR(45) NOT NULL,
  `NAME` VARCHAR(100) NULL ,
  `DESCRIPTION` VARCHAR(200) NULL ,
  PRIMARY KEY (`ID`) );

-- -----------------------------------------------------
-- Table `AD_FEATURE_PROPERTY`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `AD_FEATURE_PROPERTY` (
  `PROPERTY` VARCHAR(45) NOT NULL ,
  `FEATURE_ID` INT NOT NULL ,
  PRIMARY KEY (`PROPERTY`) ,
  CONSTRAINT `fk_AD_FEATURE_PROPERTY_AD_FEATURE1`
    FOREIGN KEY (`FEATURE_ID` )
    REFERENCES `AD_FEATURE` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
